//! Branch naming, PR title, PR body, and digest body templates.

use chrono::Utc;
use neuron_op_sweep::{SweepVerdict, VerdictStatus};

use crate::types::DailyDigest;

/// Return a branch name for a sweep PR: `sweep/<decision_id>/<date>`.
///
/// The date component uses the current UTC date in `YYYY-MM-DD` format.
pub fn branch_name(decision_id: &str) -> String {
    let date = Utc::now().format("%Y-%m-%d");
    format!("sweep/{decision_id}/{date}")
}

/// Return the PR title for a sweep verdict.
///
/// Format: `[sweep] <decision_id>: <status> — <first_line_of_narrative>`
pub fn pr_title(verdict: &SweepVerdict) -> String {
    let status = verdict_status_str(&verdict.status);
    let first = first_line(&verdict.narrative);
    format!(
        "[sweep] {}: {} \u{2014} {}",
        verdict.decision_id, status, first
    )
}

/// Render the full PR body markdown for a sweep verdict.
///
/// Includes verdict, confidence, evidence, narrative, optional proposed diff,
/// and sweep metadata.
pub fn pr_body(verdict: &SweepVerdict) -> String {
    let status = verdict_status_str(&verdict.status);

    let sources_section = if verdict.evidence.is_empty() {
        "_No evidence items recorded._".to_string()
    } else {
        verdict
            .evidence
            .iter()
            .map(|e| {
                let stance = evidence_stance_str(&e.stance);
                format!(
                    "- [{}] [{}]({}) (retrieved {})",
                    stance, e.summary, e.source_url, e.retrieved_at
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
    };

    let diff_section = if let Some(ref diff) = verdict.proposed_diff {
        format!("\n### Proposed Changes\n\n```diff\n{diff}\n```\n")
    } else {
        String::new()
    };

    format!(
        "## Sweep Verdict: {status}\n\
         \n\
         **Decision:** {decision_id}\n\
         **Confidence:** {confidence:.1} | **Supporting:** {num_supporting} | \
         **Contradicting:** {num_contradicting}\n\
         \n\
         ### Evidence\n\
         \n\
         {narrative}\n\
         \n\
         ### Sources\n\
         \n\
         {sources_section}\
         {diff_section}\n\
         ### Sweep Metadata\n\
         \n\
         - Cost: ${cost_usd:.3}\n\
         - Processor: {processor}\n\
         - Duration: {duration_secs:.1}s\n\
         - Swept at: {swept_at}\n\
         \n\
         ---\n\
         *Generated by Sweep System. Review before merging.*",
        status = status,
        decision_id = verdict.decision_id,
        confidence = verdict.confidence,
        num_supporting = verdict.num_supporting,
        num_contradicting = verdict.num_contradicting,
        narrative = verdict.narrative,
        sources_section = sources_section,
        diff_section = diff_section,
        cost_usd = verdict.cost_usd,
        processor = processor_str(&verdict.processor),
        duration_secs = verdict.duration_secs,
        swept_at = verdict.swept_at,
    )
}

/// Render a daily digest as a markdown issue body.
pub fn digest_body(digest: &DailyDigest) -> String {
    let sweeps_section = if digest.sweeps.is_empty() {
        "_No decisions swept today._".to_string()
    } else {
        digest
            .sweeps
            .iter()
            .map(|e| {
                format!(
                    "- **{}** → {} — {}",
                    e.decision_id,
                    verdict_status_str(&e.verdict),
                    e.summary
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
    };

    let pr_section = if digest.pr_activity.is_empty() {
        "_No PR activity today._".to_string()
    } else {
        digest
            .pr_activity
            .iter()
            .map(|a| {
                let url_part = a
                    .pr_url
                    .as_deref()
                    .map(|u| format!(" ({u})"))
                    .unwrap_or_default();
                format!("- **{}**: {:?}{url_part}", a.decision_id, a.action)
            })
            .collect::<Vec<_>>()
            .join("\n")
    };

    let candidates_section = if digest.new_candidates.is_empty() {
        "_None staged today._".to_string()
    } else {
        digest
            .new_candidates
            .iter()
            .map(|c| format!("- {c}"))
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        "# Daily Sweep Digest — {date}\n\
         \n\
         ## Decisions Swept\n\
         \n\
         {sweeps_section}\n\
         \n\
         ## PR Activity\n\
         \n\
         {pr_section}\n\
         \n\
         ## New Candidates\n\
         \n\
         {candidates_section}\n\
         \n\
         ## Cost Summary\n\
         \n\
         - Total cost today: ${total_cost:.3}\n\
         - Budget remaining: ${budget_remaining:.2}\n",
        date = digest.date,
        sweeps_section = sweeps_section,
        pr_section = pr_section,
        candidates_section = candidates_section,
        total_cost = digest.total_cost_usd,
        budget_remaining = digest.budget_remaining_usd,
    )
}

// ── helpers ──────────────────────────────────────────────────────────────────

/// Return the first non-empty line of a string.
fn first_line(text: &str) -> &str {
    text.lines()
        .map(str::trim)
        .find(|l| !l.is_empty())
        .unwrap_or("")
}

/// Convert [`VerdictStatus`] to a display string.
fn verdict_status_str(status: &VerdictStatus) -> &'static str {
    match status {
        VerdictStatus::Confirmed => "confirmed",
        VerdictStatus::Refined => "refined",
        VerdictStatus::Challenged => "challenged",
        VerdictStatus::Obsoleted => "obsoleted",
        VerdictStatus::Skipped => "skipped",
    }
}

/// Convert [`neuron_op_sweep::EvidenceStance`] to a display string.
fn evidence_stance_str(stance: &neuron_op_sweep::EvidenceStance) -> &'static str {
    match stance {
        neuron_op_sweep::EvidenceStance::Supporting => "supporting",
        neuron_op_sweep::EvidenceStance::Contradicting => "contradicting",
        neuron_op_sweep::EvidenceStance::Neutral => "neutral",
    }
}

/// Convert [`neuron_op_sweep::ProcessorTier`] to a display string.
fn processor_str(tier: &neuron_op_sweep::ProcessorTier) -> &'static str {
    match tier {
        neuron_op_sweep::ProcessorTier::Base => "base",
        neuron_op_sweep::ProcessorTier::Core => "core",
        neuron_op_sweep::ProcessorTier::Ultra => "ultra",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use neuron_op_sweep::{EvidenceItem, EvidenceStance, ProcessorTier, VerdictStatus};

    use crate::types::{DailyDigest, DigestEntry, PrAction, PrActivity};

    fn base_verdict() -> SweepVerdict {
        SweepVerdict {
            decision_id: "topic-3b".to_string(),
            status: VerdictStatus::Refined,
            confidence: 0.85,
            num_supporting: 3,
            num_contradicting: 1,
            cost_usd: 0.123,
            processor: ProcessorTier::Core,
            duration_secs: 6.5,
            swept_at: "2026-03-04T18:00:00Z".to_string(),
            evidence: vec![EvidenceItem {
                source_url: "https://example.com/paper".to_string(),
                summary: "Confirms the approach".to_string(),
                stance: EvidenceStance::Supporting,
                retrieved_at: "2026-03-04T17:55:00Z".to_string(),
            }],
            narrative: "Durable execution patterns remain valid.\nSee supporting evidence."
                .to_string(),
            proposed_diff: None,
        }
    }

    #[test]
    fn branch_name_format() {
        let name = branch_name("topic-3b");
        // Must start with sweep/topic-3b/ and end with YYYY-MM-DD
        assert!(name.starts_with("sweep/topic-3b/"), "got: {name}");
        let date_part = &name["sweep/topic-3b/".len()..];
        assert_eq!(
            date_part.len(),
            10,
            "date must be YYYY-MM-DD, got: {date_part}"
        );
        let parts: Vec<&str> = date_part.split('-').collect();
        assert_eq!(parts.len(), 3);
        assert_eq!(parts[0].len(), 4); // year
        assert_eq!(parts[1].len(), 2); // month
        assert_eq!(parts[2].len(), 2); // day
    }

    #[test]
    fn branch_name_with_hyphenated_id() {
        let name = branch_name("D-019");
        assert!(name.starts_with("sweep/D-019/"), "got: {name}");
    }

    #[test]
    fn pr_title_format() {
        let verdict = base_verdict();
        let title = pr_title(&verdict);
        assert!(title.starts_with("[sweep] topic-3b:"), "got: {title}");
        assert!(title.contains("refined"), "got: {title}");
        assert!(
            title.contains("Durable execution patterns remain valid"),
            "got: {title}"
        );
    }

    #[test]
    fn pr_title_first_line_only() {
        let mut v = base_verdict();
        v.narrative = "First line.\nSecond line that must not appear.".to_string();
        let title = pr_title(&v);
        assert!(title.contains("First line."), "got: {title}");
        assert!(
            !title.contains("Second line"),
            "must not contain second line; got: {title}"
        );
    }

    #[test]
    fn pr_body_contains_required_sections() {
        let verdict = base_verdict();
        let body = pr_body(&verdict);
        assert!(body.contains("## Sweep Verdict:"), "missing verdict header");
        assert!(body.contains("### Evidence"), "missing evidence section");
        assert!(body.contains("### Sources"), "missing sources section");
        assert!(
            body.contains("### Sweep Metadata"),
            "missing metadata section"
        );
        assert!(
            body.contains("*Generated by Sweep System"),
            "missing footer"
        );
        assert!(
            body.contains("https://example.com/paper"),
            "missing evidence URL"
        );
    }

    #[test]
    fn pr_body_with_proposed_diff() {
        let mut verdict = base_verdict();
        verdict.proposed_diff =
            Some("--- a/topic-3b.md\n+++ b/topic-3b.md\n@@ -1 +1 @@\n-old\n+new".to_string());
        let body = pr_body(&verdict);
        assert!(
            body.contains("### Proposed Changes"),
            "missing proposed changes section"
        );
        assert!(body.contains("```diff"), "missing diff code block");
        assert!(body.contains("-old"), "missing diff content");
    }

    #[test]
    fn pr_body_no_proposed_diff_omits_section() {
        let verdict = base_verdict();
        let body = pr_body(&verdict);
        assert!(
            !body.contains("### Proposed Changes"),
            "section must be absent"
        );
    }

    #[test]
    fn pr_body_empty_evidence_list() {
        let mut verdict = base_verdict();
        verdict.evidence = vec![];
        let body = pr_body(&verdict);
        assert!(
            body.contains("_No evidence items recorded._"),
            "got: {body}"
        );
    }

    #[test]
    fn digest_body_contains_date_and_sections() {
        let digest = DailyDigest {
            date: "2026-03-04".to_string(),
            sweeps: vec![DigestEntry {
                decision_id: "topic-3b".to_string(),
                verdict: VerdictStatus::Confirmed,
                summary: "All good.".to_string(),
            }],
            pr_activity: vec![PrActivity {
                decision_id: "topic-3b".to_string(),
                action: PrAction::AutoMerged,
                pr_url: Some("https://github.com/owner/repo/pull/7".to_string()),
            }],
            new_candidates: vec!["candidate-xyz".to_string()],
            total_cost_usd: 1.23,
            budget_remaining_usd: 8.77,
        };
        let body = digest_body(&digest);
        assert!(body.contains("2026-03-04"));
        assert!(body.contains("topic-3b"));
        assert!(body.contains("confirmed"));
        assert!(body.contains("candidate-xyz"));
        assert!(body.contains("1.230"));
    }
}
